### PR TITLE
HTTP/2: Work around QTBUG-77308, enable push

### PR DESCRIPTION
**Pull request by annulen**

### CODE REVIEW

**Comment by annulen** [comment]
@Emdek: could you check if this change has no negative impact if HTTP/2 is enabled?

**Comment by Emdek** [comment]
@annulen, sure, any other specific URLs to check?

**Comment by annulen** [comment]
Popular sites like Facebook and YouTube, or any other sites which make use of HTTP/2

**Comment by annulen** [comment]
Merged as 0acbf52c97d9da8abd497ce292cc8784be74cbd8

**Pull request closed without merging**
