### PR TITLE
[cmake] Allows macro_process_qtbase_prl_file to manage properly Apple…

### PR DESCRIPTION
**Pull request by matteoceraico**
[cmake] Allows macro_process_qtbase_prl_file to manage properly Apple's frameworks

Without this patch the following problems are verified:
1. framework names are considered as libraries
2. -framework option retrieved from prl file is considered as a library

### CODE REVIEW

**Comment by annulen** [comment]
cc @Vitallium

**Comment by annulen** [comment]
I personally don't like speed at which cruft accumulates in `macro_process_qtbase_prl_file` - such code is not very readable and maintainable. I think it would be worthwhile to separate prl parsing logic into script, and return results by e.g. generating cmake file and including it into project

**Comment by Vitallium** [comment]
I agree. Parsing dependencies (prl files) with CMake is not a good idea.

**Comment by matteoceraico** [comment]
To me, sounds good. Do you have any suggestion about how to proceed?

My libQt5Core.prl file looks like:
```
QMAKE_PRL_BUILD_DIR = /Users/username/phantomjs/src/qt/qtbase/src/corelib
QMAKE_PRO_INPUT = corelib.pro
QMAKE_PRL_TARGET = libQt5Core.a
QMAKE_PRL_CONFIG = lex yacc exceptions depend_includepath testcase_targets import_plugins import_qpa_plugin sdk rez qt_build_extra file_copies qt warn_on release link_prl app_bundle incremental global_init_link_order lib_version_first plugin_no_soname clang_pch_style static qpa no_mocdepend release qt_no_framework osx macx mac darwin unix posix gcc clang llvm compile_examples qpa largefile precompile_header sse2 sse3 ssse3 sse4_1 sse4_2 avx avx2 pcre qt_clear_installs create_prl link_prl prepare_docs qt_docs_targets no_private_qt_headers_warning QTDIR_build qt_example_installs testcase_exceptions explicitlib warning_clean c++11 exceptions moc resources optimize_full no_core_dep simd relative_qt_rpath git_build qmake_cache target_qt c++11 strict_c++ c++14 c++1z hide_symbols qt_install_headers qt_install_module create_cmake compiler_supports_fpmath create_pc create_libtool have_target staticlib objective_c c++11 thread
QMAKE_PRL_VERSION = 5.6.1
QMAKE_PRL_LIBS = -framework DiskArbitration -framework IOKit -L/usr/local/opt/openssl/lib -lz -L/Users/username/phantomjs/src/qt/qtbase/lib -lqtpcre -L/usr/local/opt/openssl/lib -lm -framework Foundation -framework CoreServices -framework AppKit -framework ApplicationServices -framework CoreFoundation

```

by parsing this file we need to extract the value of QMAKE_PRL_LIBS, then to set this:
```
            set_target_properties(${qt_target_component} PROPERTIES
                "INTERFACE_LINK_LIBRARIES" "${_link_libs}${_list_sep}${static_depends}"
                "IMPORTED_LOCATION" "${_lib_location}"
            )
```

and then to populate properly:
```
set(${_lib_name}_STATIC_LIB_DEPENDENCIES "${static_depends}")
```
by replacing "-framework FrameworkName" with the proper library (in my patch i've used the function find_library)

**Comment by annulen** [comment]
Here is a draft of script that I had in mind, when invoked as `./parse-prl.pl Core out.cmake` it reads `libQt5Core.prl` and writes `out.cmake`

```perl
#!/usr/bin/env perl

use strict;
use warnings;

my ($component_name, $out_name) = @ARGV;
my $prl_name = "libQt5$component_name.prl";
my $qmake_prl_libs;

open(my $prl, '<', $prl_name) or die "Cannot open $prl_name: $!";
while(<$prl>) {
    next unless /^QMAKE_PRL_LIBS/;
    chomp;
    if (/^QMAKE_PRL_LIBS\s+=\s+(.*)$/) {
        $qmake_prl_libs = $1;
        last;
    }
}
close $prl;

unless($qmake_prl_libs) {
    print "QMAKE_PRL_LIBS variable is undefined or empty\n";
    exit;
}

my $prl_libs = squash_prl_libs (split /\s+/, $qmake_prl_libs);

my $template = <<'END_CMAKE';

get_target_property(_link_libs Qt5::${_component} INTERFACE_LINK_LIBRARIES)
if (_link_libs)
    set(_list_sep ";")
else ()
    set(_list_sep "")
endif ()
set_target_properties(Qt5::${_component} PROPERTIES
    "INTERFACE_LINK_LIBRARIES" "${_link_libs}${_list_sep}${_libs}"

set(Qt5${_component}_STATIC_LIB_DEPENDENCIES "${_libs}")

unset(_component)
unset(_libs)
END_CMAKE

open(my $out, '>', $out_name) or die "Cannot open $out_name for writing: $!";
print $out qq/set(_component "$component_name")\n/;
print $out qq/set(_libs "$prl_libs")\n/;
print $out $template;
close $out;

sub squash_prl_libs {
    my @libs = @_;
    my @result;
    for (my $i = 0; $i < $#libs; ++$i) {
        my $lib = $libs[$i];
        if ($lib eq '-framework') {
            push @result, "$libs[$i] $libs[$i + 1]";
            ++$i;
        } else {
            push @result, $lib;
        }
    }
    return join ';', @result;
}

```

**Comment by annulen** [comment]
End result  should be usable in cmake without `find_library` hack

**Comment by annulen** [comment]
I've opened PR #338 with script added

**Comment by annulen** [comment]
I've moved your change to #338 and added some fixes to cmake part

**Comment by annulen** [comment]
In particular, all regexes are now moved to where they belong, i.e. perl

**Comment by annulen** [comment]
Does everything work fine now?

**Comment by matteoceraico** [comment]
yes, i just compiled everything without problems

**Comment by annulen** [comment]
Merged as a part of #338

**Pull request closed without merging**
