### PR TITLE
Executable bit set and rename checker

### PR DESCRIPTION
**Pull request by RAJAGOPALAN-GANGADHARAN**

### CODE REVIEW

**Comment by annulen** [comment]
Fix looks good, but patches have been merged already so it should be done in a separate commit.

Also, installed-files-checker.py is missing license header, and commented code still has references to the old name.

**Comment by annulen** [comment]
On the other hand I can just revert checked patch and apply a new version, maybe it's even better from viewpoint of atomic history

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
So i can leave it as such? ( cause initially i thought we might just revert the old three commits and apply these three cause that would be much cleaner) or should i make a new commit.

**Comment by annulen** [comment]
Merged, with fixup in c67f1bdd9636fd38ade44af14e17f03b427f37ef

**Comment by annulen** [comment]
Reverting three commit is to messy, but only the last commit was changed (rebasing your branch proves there are no more changes).

**Comment by annulen** [comment]
Seems like we are badly missing CI for qtwebkit-stable. I've made initial attempt in https://github.com/qtwebkit/qtwebkit/pull/971. General idea is to merge qtwebkit-5.212 into it before building, however I've tried to make it "optimal" and end result is too messy

**Pull request closed without merging**
