### PR TITLE
Test for page scroll when using findText()

### PR DESCRIPTION
**Pull request by Emdek**

### CODE REVIEW

**Comment by annulen** [comment]
Improved version: 77634ac77cca304ad22a859e3960420635382dc4

**Comment by annulen** [comment]
So, should I merge 77634ac77cca304ad22a859e3960420635382dc4 as is and close this PR?

**Comment by Emdek** [comment]
@annulen, looks good to me, although it could make sense to split out that helper code.

**Comment by annulen** [comment]
Merged as 37d8e15330b298a1a8ea4302ccdce1c33c109143

**Pull request closed without merging**
