### PR TITLE
Fix test browser build without Qt OpenGL

### PR DESCRIPTION
**Pull request by ariya**

### CODE REVIEW

**Comment by annulen** [comment]
Thanks!

**Comment by ariya** [comment]
Thanks for the merge! Shall I upstream this or will you take care of that?

**Comment by annulen** [comment]
This is not needed in upstream actually. Qt patch that added QOpenGLWidget support removed #ifdef around this variable, but I haven't started process of mass-merging Qt patches yet (today I've got LayoutTests rolling so I can start it really soon). Under "Qt patches" I mean patches which were not merged to trunk, but went directly to gerrit and/or qt-5x2 branch.

Also, this particular line is not present in Qt upstream. It was added by me because I cannot enable AC by default, because software mode of AC does not work yet (in fact, GL mode is not fully merged here, but it works for me locally with a few crude hacks; software mode requires restoring class that was removed from trunk because of being broken at some point, so it's harder, and also not needed for my employer).

**Comment by annulen** [comment]
But if there are changes which affect Qt branch too, it's always better to submit patches personally.

**Pull request merged**
