### PR TITLE
Add #if guards for QT_GESTURE_EVENTS

### PR DESCRIPTION
**Pull request by cadubentzen**
Compilation was breaking when configuring with the following arguments:

```
$ cmake ../.. -DPORT=Qt \
    -DENABLE_WEBKIT2=OFF \
    -DENABLE_DEVICE_ORIENTATION=OFF \
    -DENABLE_GEOLOCATION=OFF \
    -DENABLE_OPENGL=OFF \
    -DENABLE_QT_GESTURE_EVENTS=OFF \
    -DENABLE_TOUCH_EVENTS=OFF \
    -DENABLE_API_TESTS=OFF \
    -DENABLE_TOOLS=OFF \
    -DENABLE_PRINT_SUPPORT=OFF 
```

### CODE REVIEW

**Comment by cadubentzen** [comment]
It seems like #670 needs to applied in qtwebkit-stable for Travis CI to work.. Otherwise all PR checks will fail.

**Comment by annulen** [comment]
Ok

**Comment by annulen** [comment]
I think proper solution is to avoid enabling TOUCH_ADJUSTMENT if QT_GESTURE_EVENTS is OFF

```diff
diff --git a/Source/cmake/OptionsQt.cmake b/Source/cmake/OptionsQt.cmake
index 57ea7051dff..de180ee56f7 100644
--- a/Source/cmake/OptionsQt.cmake
+++ b/Source/cmake/OptionsQt.cmake
@@ -294,6 +294,8 @@ WEBKIT_OPTION_DEPEND(ENABLE_MEDIA_SOURCE USE_GSTREAMER)
 
 WEBKIT_OPTION_DEPEND(ENABLE_QT_WEBCHANNEL ENABLE_WEBKIT2)
 
+WEBKIT_OPTION_DEPEND(ENABLE_TOUCH_ADJUSTMENT ENABLE_QT_GESTURE_EVENTS)
+
 # While it's possible to have UI-less NPAPI plugins without X11, we don't support this case yet
 if (UNIX AND NOT APPLE)
     WEBKIT_OPTION_DEPEND(ENABLE_NETSCAPE_PLUGIN_API ENABLE_X11_TARGET
```

**Comment by cadubentzen** [comment]
You are right. Just applied the suggest patch and it works fine! 

Pushed again with the proper solution.

**Comment by cadubentzen** [comment]
Squashed the commits into one, as the it's a only-liner.

**Pull request merged**
