### PR TITLE
Correct timestamp for requestAnimationFrame()

### PR DESCRIPTION
**Pull request by ObserverHerb**
Finally tracked down the different between requestAnimationFrame() and performance.now(). Apparently, according to CurrentTime.h, currentTime() shouldn't be used directly unless absolutely necessary.

### CODE REVIEW

**Comment by herbmillerjr** [comment]
Quick test case:
[test.zip](https://github.com/annulen/webkit/files/1882795/test.zip)

**Comment by annulen** [comment]
Looks reasonable. But `!USE(REQUEST_ANIMATION_FRAME_TIMER)` code path should probably be removed anyway

**Comment by annulen** [comment]
>Apparently, according to CurrentTime.h, currentTime() shouldn't be used directly unless absolutely necessary.

That's correct, but in this particular case signature says it all

    void FrameView::serviceScriptedAnimations(double monotonicAnimationStartTime)

**Comment by herbmillerjr** [comment]
What's the history behind that code path? I remember talking about it once before but don't know if I asked about that.

**Comment by annulen** [comment]
It originates from Chromium, Qt port uses it since https://bugs.webkit.org/show_bug.cgi?id=88638 While change was justified there, in fact it ruins results of MotionMark, also it was removed in trunk since then so it probably needs to be ditched

**Comment by herbmillerjr** [comment]
Thanks! Is removing it enough or is there more I need to do like bringing over new code from trunk to fill in the gap?

**Comment by annulen** [comment]
This patch switches code path:

```diff
diff --git a/Source/WTF/wtf/Platform.h b/Source/WTF/wtf/Platform.h
index f3d72521721..97c387dd146 100644
--- a/Source/WTF/wtf/Platform.h
+++ b/Source/WTF/wtf/Platform.h
@@ -1027,7 +1027,7 @@
 #define USE_VIDEOTOOLBOX 1
 #endif
 
-#if PLATFORM(COCOA) || PLATFORM(GTK) || (PLATFORM(WIN) && !USE(WINGDI))
+#if PLATFORM(COCOA) || PLATFORM(GTK) || PLATFORM(QT) || (PLATFORM(WIN) && !USE(WINGDI))
 #define USE_REQUEST_ANIMATION_FRAME_TIMER 1
 #endif
 
```
After that all `!USE(REQUEST_ANIMATION_FRAME_TIMER)` code becomes dead

**Comment by herbmillerjr** [comment]
Rebased with solution discussed here. Should the affirmative `USE(REQUEST_ANIMATION_FRAME_TIMER)` conditions be removed and the code just made the default code path? Should I have left `!USE(REQUEST_ANIMATION_FRAME_TIMER)` stuff in the webkit code and just removed it from the Qt portions?

**Comment by herbmillerjr** [comment]
What broke the style checker? Can I rerun it somehow?

**Comment by herbmillerjr** [comment]
Rebased onto qtwebkit-stable.

**Pull request closed without merging**
